#!/bin/bash

export RUBY_GC_MALLOC_LIMIT_MAX=64000000
export RUBY_GC_OLDMALLOC_LIMIT_MAX=64000000
export RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.3
export APP_DIR=/opt/varnish-test/current
RAILS_ENV=${RAILS_ENV:-production}

cp $APP_DIR/docker/nginx.conf /etc/nginx/nginx.conf
cp $APP_DIR/docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

rake db:migrate assets:precompile
/usr/bin/supervisord -n
